name: aiyy
base: core22
version: '0.2'
summary: CLI assistant for technical information
description: |
  Get technical information on the command line with ease using AIY. Simply type in your question as the prompt and 
  receive a beautifully formatted and helpful response. This snap also has options for resetting the API key and 
  toggling warnings.
architectures:
  - build-on: [amd64]
grade: devel
confinement: devmode

apps:
  aiyy:
    command: resources/bin/aiy.sh

parts:
  aiyy-part:
    plugin: python
    source: https://github.com/visioninit/aiy.git
    python-packages:
      - wheel
      - pip
      - openai==0.26.4
      - rich==13.3.1
    override-build: |
      craftctl default
      install -m755 $CRAFT_PART_SRC/resources/bin/aiy.sh $CRAFT_PART_INSTALL/resources/bin/