name: aiyy
base: core20
version: '0.1'
summary: CLI assistant for technical information
description: |
  Get technical information on the command line with ease using AIY. Simply type in your question as the prompt and 
  receive a beautifully formatted and helpful response. This snap also has options for resetting the API key and 
  toggling warnings. 
architectures:
  - build-on: [amd64]
grade: devel
confinement: devmode

apps:
  aiyy:
    command: bin/aiyy.aiy
    plugs: [home, network, network-bind, removable-media]


parts:
  aiyy-part:
    plugin: python
    source: ../.