name: Windows Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-win:
    if: contains(github.event.head_commit.message, '[build-win]' ) || github.event_name == 'workflow_dispatch' # only run if commit message contains [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Windows Binary
        run: |
          pyinstaller --onefile aiy.py --distpath dist/
          mkdir out && cd dist && Compress-Archive -Path . -DestinationPath ../out/aimm-windows-binary.zip
          cd ..
      - name: Install pynsist
        run: |
          pip install pynsist
      - name: Build Windows-Installer
        run: |
          cp resources/install/win/installer.cfg installer.cfg
          pynsist installer.cfg
          cp build/nsis/aimm-windows-installer.exe out/
      - name: 📂 Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          state-name: '.ftp-deploy-sync-state-win.json'
          local-dir: "out/"
          server-dir: ""
      - name: Upload Release Windows
        uses: actions/upload-artifact@v3
        with:
          name: Windows Binary
          path: out/aimm-windows-installer.exe
